#! /bin/sh

DATEFMT=${DATEFMT:-"+%a %d.%m.%Y %H:%M:%S"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}

OPTIND=1
while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

case "$BLOCK_BUTTON" in
  1|2|3) 

	# yad takes the position of the upper left corner of the popup
	# we need to find the top right of the current output
	rect=$(i3-msg -t get_workspaces | jq '.[] | select(.focused == true).rect')
	posX=$(echo "$rect" | jq '.x + .width - 300')
	posY=$(echo "$rect" | jq '.y')

	i3-msg -q "exec yad --calendar \
	    --undecorated --fixed \
	    --close-on-unfocus --no-buttons \
	    --posx=$posX --posy=$posY \
	    > /dev/null"
esac
echo "$(date -I'seconds')"
echo "$(date "$SHORTFMT")"

